theme: jekyll-theme-chirpy
title: Lawgical Archives
tagline: Your Weekly Dose of Legal Insight
description: >-
  A blog by Diksha Soni covering legal issues, opinions, and research.
lang: en
timezone: Asia/Kolkata
url: "https://diksha-soni01.github.io"
baseurl: ""
github:
  username: diksha-soni01
social:
  name: Diksha Soni
  email: diksha932@gmail.com
  links:
    - https://github.com/diksha-soni01
    - https://www.linkedin.com/in/diksha-soni-9b5585233
paginate: 10
theme_mode: light
toc: true
